id: dancetrack
dataset:
  id: dancetrack
  root: boxmot/engine/eval/trackeval/data/test1
  layout: mot
  box_type: aabb
  splits:
    val: val
    test: test
  default_split: val
  classes:
    1: pedestrian
  no_gt_splits:
  - test
download:
  dataset: ''
  runs: ''
detector:
  id: yolox_x_dancetrack
  model: models/yolox_x_dancetrack.pt
  url: https://huggingface.co/Lekim89/yolox/resolve/main/yolox_x_dancetrack.pt
  imgsz:
  - 800
  - 1440
  conf: 0.01
  classes:
    0: person
reid:
  id: lmbn_n_duke
  model: ''
  url: ''
  device: ''
  half: true
  preprocess: resize
